contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/antfu/contribute
    about: Please read through before making contributions.
  - name: ğŸ’¬ Harlan's Discord Server
    url: https://discord.gg/vXxb6CZPNy
    about: Want to discuss / chat with the community? Here you go!
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: Reproduction is important for maintainers to help on your issues! Check the article by antfu to learn more
